MODEL:
  NAME: 'resnet50_ifn'
  LAST_STRIDE: 2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  HF_PROB: 0.5 # random horizontal flip
  PADDING: 10

  RE: False # enable random erasing
  RE_PROB: 0.5 # random erasing probability

DATASETS:
  SOURCE: ['Market-1501', 'DukeMTMC-reID', 'CUHK03', 'CUHK02', 'CUHK-SYSU']
  TARGET: ['PRID2011', 'GRID', 'VIPeR', 'i-LIDS']
  # STORE_DIR: './datasets'
  # STORE_DIR: '/Users/linshan/Pictures/Person_ReID_Datasets'
  STORE_DIR: '../dsta/Datasets'
  
DATALOADER:
  NUM_WORKERS: 0

SOLVER:
  LOSS: 'softmax'
  MAX_EPOCHS: 160
  IMS_PER_BATCH: 64

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 256
  LOAD_EPOCH: 160

OUTPUT_DIR: "./checkpoint/Dual_Norm_Offical"
# DEVICE: "cpu"
DEVICE: "cuda:0"
