MODEL:
  NAME: 'DenseNet'
  #NUM_CLASSES: 632

INPUT:
  SIZE_TRAIN: [224, 224] # From paper
  SIZE_TEST: [224, 224]
  PROB: 0.5 
  PADDING: 0 

DATASETS:
  NAMES: ('DukeMTMC-reID') 
  STORE_DIR: '/home/GTA'

FILTERS:
  LOCATION: ['beach','carpark','countryside','fbi','greenery','indoorcarpark','pier','subway','urbanstreet'] 
  WEATHER: ['CLEAR'] #CLEAR, CLOUDS, RAIN
  TIME: ['13'] #9, 13, 17, 21. Remember to pass value as a str NOT int
  ANIMATION: ['walk'] #walk or run
  CAM_HEIGHT: ['surveillance'] #person, surveillance, drone
  PID_RANGE: [] #give a range i.e. [1, 500] gives the first 500 pid
  YAW_ANGLE: [1,8] #give the range of yaw angles, i.e. [1,8] gives the full range of angles from 1 to 8.
  QUERY_ANGLE: [1] #give the absolute query angles.


DATALOADER:
  SAMPLER: 'capsule'
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 100 
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.00005 
  WEIGHT_DECAY_BIAS: 0.00005 
  IMS_PER_BATCH: 64 

  STEP: 40
  GAMMA: 0.1

  CHECKPOINT_PERIOD: 10
  EVAL_PERIOD: 10 

TEST:
  IMS_PER_BATCH: 128
  LOAD_EPOCH: 100

OUTPUT_DIR: "./checkpoint/ReIDCaps/DukeMTMC"
DEVICE: "cuda"
