MODEL:
  NAME: 'ResNet50'
  
INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('GTA_Uniform') #Switch between GTAv3 and GTA_long 

FILTERS:
  LOCATION: ['fbi'] 
  WEATHER: ['RAIN'] #CLEAR, CLOUDS, RAIN
  TIME: ['13'] #9, 13, 17, 21. Remember to pass value as a str NOT int
  ANIMATION: ['walk'] #walk or run
  CAM_HEIGHT: ['person'] #person, surveillance, drone
  PID_RANGE: [] #give a range i.e. [1, 500] gives the first 500 pid
  YAW_ANGLE: [1,8] #give the range of yaw angles, i.e. [1,3,7,8] gives the first 4 yaw angles
  QUERY_ANGLE: [1] #give the absolute query angles


DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEP: 40
  GAMMA: 0.1

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256
  LOAD_EPOCH: 120
  

OUTPUT_DIR: "./checkpoint/GTA_uniform/Softmax_Triplet_BS64"
DEVICE: "cuda:7"
