MODEL:
  NAME: 'ResNet50'

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('GTAv3')

FILTERS:
  LONGTERM: False
  LOCATION: []
  WEATHER: [] #CLEAR, CLOUDS, RAIN
  TIME: [] #9, 13, 17, 21
  ANIMATION: [] #walk or run
  CAM_HEIGHT: [] #person, surveillance, drone
  PID_RANGE: [] #give a range i.e. [1, 500] gives the first 500 pid)
  YAW_ANGLE: [] #give a range i.e. [1,4] gives the first 4 yaw angles

DATALOADER:
  SAMPLER: 'softmax'
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEP: 40
  GAMMA: 0.1

  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20

TEST:
  IMS_PER_BATCH: 256

OUTPUT_DIR: "./checkpoint/GTA/Softmax_BS64"
DEVICE: "cuda:0"